version: "3"

services:
  dynamorio-riscv64:
    restart: always
    container_name: dynamorio-riscv64-compile
    build: .
    volumes:
      - ./dynamorio:/dynamorio:rw
    command: bash
    tty: true # docker run -i
    stdin_open: true # docker run -t 
